### ISSUE TITLE
Cannot transpile active pseudo class and arbitrary value

### ISSUE THREAD

**Issue by karyanayandi** [sudoaugustin/tailpile#3]
Cannot transpile active pseudo class and arbitrary value.

![Cheese_22 06 21_01 29 05](https://user-images.githubusercontent.com/25613501/174660396-6c1abaa7-ab82-47af-8e44-f83ddf1c9ceb.png)

**Comment by sudoaugustin** [comment]
@karyanayandi  Did u add `tailwind.config.js` in Tailpile config? Have u tried this? The problem is your `tailwind.config.js` wasn't been used by Tailpile.

<img width="758" alt="Screen Shot 2022-10-19 at 12 41 46 PM" src="https://user-images.githubusercontent.com/57541158/196610876-2cd1c362-4c56-49a1-bd54-0d6ddd92c972.png">

**Comment by karyanayandi** [comment]
> @karyanayandi Did u add `tailwind.config.js` in Tailpile config? Have u tried this? The problem is your `tailwind.config.js` wasn't been used by Tailpile.
> 
> <img alt="Screen Shot 2022-10-19 at 12 41 46 PM" width="758" src="https://user-images.githubusercontent.com/57541158/196610876-2cd1c362-4c56-49a1-bd54-0d6ddd92c972.png">

thank you for your solution. i'll try
